# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(947, 842)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(260, 0, 681, 801))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.horizontalLayoutWidget_2)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 251, 801))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.fileView = QtGui.QTreeView(self.verticalLayoutWidget)
        self.fileView.setEnabled(False)
        self.fileView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.fileView.setAlternatingRowColors(True)
        self.fileView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.fileView.setSortingEnabled(False)
        self.fileView.setObjectName(_fromUtf8("fileView"))
        self.verticalLayout.addWidget(self.fileView)
        self.classView = QtGui.QTreeView(self.verticalLayoutWidget)
        self.classView.setEnabled(False)
        self.classView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.classView.setObjectName(_fromUtf8("classView"))
        self.verticalLayout.addWidget(self.classView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 947, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionShow_Strings = QtGui.QAction(MainWindow)
        self.actionShow_Strings.setEnabled(False)
        self.actionShow_Strings.setObjectName(_fromUtf8("actionShow_Strings"))
        self.actionShow_Type = QtGui.QAction(MainWindow)
        self.actionShow_Type.setCheckable(False)
        self.actionShow_Type.setEnabled(False)
        self.actionShow_Type.setObjectName(_fromUtf8("actionShow_Type"))
        self.actionShow_Header = QtGui.QAction(MainWindow)
        self.actionShow_Header.setEnabled(False)
        self.actionShow_Header.setObjectName(_fromUtf8("actionShow_Header"))
        self.actionShow_Prototype = QtGui.QAction(MainWindow)
        self.actionShow_Prototype.setEnabled(False)
        self.actionShow_Prototype.setObjectName(_fromUtf8("actionShow_Prototype"))
        self.actionShow_Method = QtGui.QAction(MainWindow)
        self.actionShow_Method.setEnabled(False)
        self.actionShow_Method.setObjectName(_fromUtf8("actionShow_Method"))
        self.actionShow_XRef_Graph = QtGui.QAction(MainWindow)
        self.actionShow_XRef_Graph.setEnabled(False)
        self.actionShow_XRef_Graph.setObjectName(_fromUtf8("actionShow_XRef_Graph"))
        self.actionShow_Method_2 = QtGui.QAction(MainWindow)
        self.actionShow_Method_2.setEnabled(False)
        self.actionShow_Method_2.setObjectName(_fromUtf8("actionShow_Method_2"))
        self.actionShow_Field = QtGui.QAction(MainWindow)
        self.actionShow_Field.setEnabled(False)
        self.actionShow_Field.setObjectName(_fromUtf8("actionShow_Field"))
        self.actionInformation = QtGui.QAction(MainWindow)
        self.actionInformation.setObjectName(_fromUtf8("actionInformation"))
        self.actionInformation_2 = QtGui.QAction(MainWindow)
        self.actionInformation_2.setObjectName(_fromUtf8("actionInformation_2"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionShow_Header)
        self.menuEdit.addAction(self.actionShow_Strings)
        self.menuEdit.addAction(self.actionShow_Type)
        self.menuEdit.addAction(self.actionShow_Method)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionShow_XRef_Graph)
        self.menuEdit.addAction(self.actionShow_Method_2)
        self.menuEdit.addAction(self.actionShow_Field)
        self.menu.addAction(self.actionInformation)
        self.menu.addAction(self.actionInformation_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "APK Static Analyzer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menu.setTitle(_translate("MainWindow", "?", None))
        self.actionOpen.setText(_translate("MainWindow", "Open APK", None))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Open an APK file", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setStatusTip(_translate("MainWindow", "Quit the application", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionShow_Strings.setText(_translate("MainWindow", "Show Strings", None))
        self.actionShow_Type.setText(_translate("MainWindow", "Show Types", None))
        self.actionShow_Header.setText(_translate("MainWindow", "Show Header", None))
        self.actionShow_Prototype.setText(_translate("MainWindow", "Show Prototype", None))
        self.actionShow_Method.setText(_translate("MainWindow", "Show Methods", None))
        self.actionShow_XRef_Graph.setText(_translate("MainWindow", "Show XRef  Graph", None))
        self.actionShow_Method_2.setText(_translate("MainWindow", "Show Methods", None))
        self.actionShow_Field.setText(_translate("MainWindow", "Show Fields", None))
        self.actionInformation.setText(_translate("MainWindow", "Readme", None))
        self.actionInformation_2.setText(_translate("MainWindow", "Information", None))

